### ISSUE TITLE
Children as second argument out of line with API

### ISSUE THREAD

**Issue by ALMaclaine** [krakenjs/jsx-pragmatic#2]
Isn't this out of step with the React API where children is on the props variable?

https://reactjs.org/docs/composition-vs-inheritance.html#containment

Is there any particular reason this decision was made and will it persist?

**Comment by bluepnume** [comment]
It's a fair callout -- but in fairness; this falls more on the side of "How React works" rather than "How JSX works". And if you're using the react renderer that's part of jsx-pragmatic it will take care of this for you automatically.

Happy to consider changing this though. Is your concern being able to tear out jsx-pragmatic in future and replace with vanilla react, or do you have other concerns?

**Comment by ALMaclaine** [comment]
It really does boil down to that, would make it quite a bit easier to trade components between jsx-pragmatic and react.

I suppose I don't know much about `"How React works" rather than "How JSX works"` and when asking the question I thought you might have made the decision for a specific reason that I was unaware of. If the decision was arbitrary I think it's beneficial to the wider community to maintain consistency. It might be lofty wishing, but JSX seems like a robust solution to templating and component dependency management that might remain with us for a while. It's starting to seem like there's no shortage of things it can be adapted to, and I think maintaining some consistency would help things flourish, if only because components were more universal.

I suppose it boils down to trying to keep JSX as pure as possible to it's original React usage API so we limit the proliferation of different variations or flavors of components, fragmenting the community and spreading out efforts where they could be combined. Especially in regards to dummy components, I'd love to see a day where you write your components in one format (JSX) and they work in any framework of your choosing and natively. This project is one big step in that direction, so for that reason I'd like to suggest maintaining consistency wherever possible.

Thank you for your consideration of this proposal

**Comment by bluepnume** [comment]
This definitely deserves some serious thought 👍 

For what it's worth, there are a few other areas where jsx-pragmatic diverges from React:

- `class` instead of `className`. The intention here is to have the jsx map more closely to the resulting html or dom -- and jsx inherently has no restriction against passing a `class` prop. In fact I think in future versions of React, and I know Preact allows this, they're going to switch back to `class`
- jsx-pragmatic will accept `undefined` returned from a function component, and will not insist on `null`

At its heart, when jsx sees an expression like `<Foo bar="baz" />`, it basically delegates all of the following to the `@pragma` that's selected:

- Here's a function called `Foo` -- call it immediately, or call it later, or call it multiple times, or don't call it at all, that's up to you
- Here's an object containing the literal props that were passed
- Here's an array of any rendered children

The rest is entirely left up to whatever renderer or framework consumes the JSX. So for example -- it is more 'React-like' to not call `Foo` immediately -- it will be called when the component is mounted, and multiple times after that on re-renders. But if we're rendering HTML or DOM, we have to call `Foo` immediately to built the tree. Same with the things passed to `Foo` -- jsx doesn't dictate that you pass props as the first argument, or pass it at all.

So the idea with jsx-pragmatic was to say -- let's totally separate what jsx gives us by itself, and what the renderer/framework gives us -- let's separate those concerns, and allow anyone to build a renderer that can, at run-time, translate a jsx node into any other form. Be it html, dom, react, an svg, xml, json, or whatever else.

So part of the intention there is to be decoupled from the design decisions that are baked into React (like `className` or `props.children`), that aren't inherent to jsx.

That said, it's a strong argument that having *fairly* interoperable functional components would probably make everyone's lives easier, coming from the familiarity of React. I think that `children` is a fundamentally different concept to `props`, which is why I kept them separate. But it's possible that's not a convincing enough reason to break from tradition.

**Comment by ALMaclaine** [comment]
Reading through, those seem like very valid reasons for the choices you've made, I will not pretend to have the scope of knowledge or experience to truly weight all the choices as you have.

So far I haven't run into actual issues because of children, it's just different than React. But the lack of support for className is causing problems for typescript TSX which complains about using class instead of className.

This might be a tall order, but is it possible to modularize jsx-pramatic and add something along the line of "loaders" from babel so it's possible to choose amongst the different API's...?

**Comment by bluepnume** [comment]
> But the lack of support for className is causing problems for typescript TSX which complains about using class instead of className.

Yeah, this is definitely a known problem with typescript. See https://github.com/Microsoft/TypeScript/issues/21699 -- the crux of the issue is that typescript doesn't look at custom jsx pragmas to decide how to type the function. Again a problem with being too coupled to React :)

> This might be a tall order, but is it possible to modularize jsx-pramatic and add something along the line of "loaders" from babel so it's possible to choose amongst the different API's...?

I'm not clear on what you're suggesting here. jsx-pragmatic already lets you choose what target you want to render to, right?

**Comment by ALMaclaine** [comment]
Ahhhhh honestly at this stage I don't even know I have a valid position or understanding to make suggestions.  I'm just going to leave well enough alone and take the library as you decide to offer it. Is there any advice you have on how to resolve the class/className issue?

**Comment by ALMaclaine** [comment]
I realized I can edit the renderer to switch className to class. Thanks for all your time, this is really great project, look forward to seeing how it grows.
