### ISSUE TITLE
Without library?

### ISSUE THREAD

**Issue by JanSemorad** [krakenjs/jsx-pragmatic#4]
You wrote:
                              **"We're not tying ourselves to any particular framework yet"**

but in Hello World I received following error:
                              **Uncaught SyntaxError: Unexpected token <**

See:
                             https://next.plnkr.co/edit/D2PlLSAmFQSW85mM?preview

What is necessary to do to make **the most simply** Hello world directly in the browser?

Thanks.

**Comment by woubuc** [comment]
JSX isn't supported directly by Javascript, so you'll still need to transpile the JSX code to the underlying function calls (e.g. with babel or typescript).

The point of this library is that, after transpiling the code, you don't need the entire React framework if you just want to render some JSX elements. Using the `/* @jsx node */` comment on top of your file (or setting the `jsxFactory` setting in your tsconfig) will make sure the JSX is converted to generic `node()` functions rather than `React.createElement()` calls, which are React-specific.
